[profile.default]
src = "src"
out = "out"
libs = ["lib"]
legacy = true
optimizer = true
optimizer_runs = 200
build_info = true



[rpc_endpoints]
rootstock_testnet = "https://public-node.testnet.rsk.co"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
